project:
  type: default
  output-dir: _site
  post-render:
    - assets/scripts/slides-to-pdf.sh

format:
  coeos-revealjs:
    logo: https://raw.githubusercontent.com/mcanouil/hex-stickers/main/SVG/mc.svg
    include-after-body:
      - text: |
          <style>.reveal .slide-logo { z-index: unset; }</style>
          <style>
            // .reveal .slides { border: 1px solid #fafafa; }
          </style>
