name: Release Reveal.js Slides

on:
  workflow_dispatch:
    inputs:
      quarto:
        description: "Quarto version"
        required: true
        default: "release"
        type: string

permissions:
  contents: write
  pull-requests: write
  id-token: write
  pages: write

jobs:
  release:
    uses: mcanouil/quarto-workflows/.github/workflows/release-revealjs.yml@main
    secrets: inherit
    with:
      quarto: "${{ github.event.inputs.quarto }}"
